smartqa:
  upload-dir: uploads

spring:
  application:
    name: smartqa
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5432/smartqa
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        hbm2ddl: 
          auto: update